#!/bin/bash

set -e

echo \
"
.##.....##.##....##..######...#######..##......
.###...###..##..##..##....##.##.....##.##......
.####.####...####...##.......##.....##.##......
.##.###.##....##.....######..##.....##.##......
.##.....##....##..........##.##..##.##.##......
.##.....##....##....##....##.##....##..##......
.##.....##....##.....######...#####.##.########
..............................................
..######..########.########..##.....##.########.########.
.##....##.##.......##.....##.##.....##.##.......##.....##
.##.......##.......##.....##.##.....##.##.......##.....##
..######..######...########..##.....##.######...########.
.......##.##.......##...##....##...##..##.......##...##..
.##....##.##.......##....##....##.##...##.......##....##.
..######..########.##.....##....###....########.##.....##
.........................................................
.########..##....##....########.########...######..
.##.....##..##..##........##....##.....##.##....##.
.##.....##...####.........##....##.....##.##.......
.########.....##..........##....########..##...####
.##.....##....##..........##....##...##...##....##.
.##.....##....##..........##....##....##..##....##.
.########.....##..........##....##.....##..######..
...................................................
"
echo
echo "MYSQL DATABASE SETUP"

while [[ -z "$SERVER_ID" ]]; do
    read -p "Enter [MySQL SERVER_ID] : " SERVER_ID
done
export SERVER_ID=$SERVER_ID
export PREF_HOSTNAME=mysql-server-$SERVER_ID
echo "HOSTNAME: "$PREF_HOSTNAME

while [[ -z "$MYSQL_DATABASE" ]]; do
    read -p "Enter [MySQL Database]: " MYSQL_DATABASE
done
export MYSQL_DATABASE=$MYSQL_DATABASE

while [[ -z "$MYSQL_USER" ]]; do
    read -p "Enter [MySQL User]: " MYSQL_USER
done
export MYSQL_USER=$MYSQL_USER

while [[ -z "$MYSQL_PASSWORD" ]]; do
    read -sp "Enter [MySQL Password]: " MYSQL_PASSWORD
    echo
done
export MYSQL_PASSWORD=$MYSQL_PASSWORD

while [[ -z "$MYSQL_ROOT_PASSWORD" ]]; do
    read -sp "Enter [MySQL Root Password]: " MYSQL_ROOT_PASSWORD
    echo
done
export MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

echo

echo "EXEC: docker compose up -d "$@""
docker compose up -d "$@"
echo
echo
